version: '3.4'

services:
  # without-volume:
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile
  #   image: without-volume
  #   ports:
  #     - '3001:3000'
  nextjs:
    image: node:16-alpine
    working_dir: "/app"
    volumes:
       - ${PWD}/..:/app:cached
    ports:
      - "3000:3000"
    command: "npm run dev"